### ISSUE TITLE
Task List: Prototype MySQL Database for testing purposes

### ISSUE THREAD

**Issue by Imipenem** [Zethson/Quarrel#5]
Task list for our prototype database connection/processing using MySQL in AndroidStudio. This is only for testing purposes and will be replaced with "not so" bad practice by accessing our database through a RESTful webservice.

- [ ] Finding a suitable (first for free) database host
- [ ] Connect to remote database using JDBC 
- [ ] Create test dummies 
- [ ] Populate database with dummies and perform some tests on this set (including login, registration 
        testingt at least)
- [ ] Create new task list for roadmapping/implementing a RESTful webservice
